/**
 * GET /openapi.json — serve the static OpenAPI 3.0 spec for the CUIT SaaS API.
 *
 * Generated by `pnpm openapi:dump` in the cuit-saas repo. Same source of
 * truth as the runtime API server's /openapi.json endpoint.
 */
import spec from "@/content/openapi.json";

export const dynamic = "force-static";

export function GET() {
  return new Response(JSON.stringify(spec, null, 2) + "\n", {
    headers: {
      "content-type": "application/json; charset=utf-8",
      "cache-control": "public, max-age=300, s-maxage=300",
      "access-control-allow-origin": "*",
    },
  });
}
