// build.mjs — esbuild IIFE bundle for the Chrome extension content script.
//
// Usage:
//   node build.mjs                  # writes content.js in this directory
//   node build.mjs --outfile=<path> # writes to a custom path (used by tests)
//
// Deterministic output contract:
//   - minify: false   — symbol names preserved; popup.js method lookup stays correct
//   - sourcemap: false — no path-dependent output; byte-identical across machines
//   - banner: fixed string without timestamps — no non-deterministic bytes
//   - format: 'iife'  — Chrome MV3 content scripts in world:MAIN cannot use ESM imports
//   - Post-processed to single-quoted strings: esbuild normalises to double quotes;
//     post-processing converts double→single so the bundle matches the TS source style
//     and the test assertions (which grep for 'log', 'console', 'error-event', etc.)
//
// Exported API:
//   buildExtension(outfile: string): Promise<void>
//     Used by test/build-parity.test.ts to build into temp files for the
//     reproducibility assertion.  Must remain the single canonical build path
//     so CLI usage and test usage exercise the same esbuild config.

import * as esbuild from 'esbuild';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ENTRY = path.join(HERE, 'src', 'content.entry.ts');
const DEFAULT_OUTFILE = path.join(HERE, 'content.js');

const BANNER =
  '// GENERATED by build.mjs from @haywork/cuit-recorder — DO NOT EDIT BY HAND. Run `pnpm -F @haywork/recorder-extension build`.';

/**
 * Post-process the esbuild output to normalise string literal quoting.
 *
 * esbuild always produces double-quoted string literals.  The extension codebase
 * and its test assertions use single quotes as the canonical style.  This function
 * converts every double-quoted string literal in the source text to single-quoted,
 * handling the common escape cases.  It also removes the spurious `"use strict";`
 * line that esbuild injects when transpiling an ES module to IIFE — the IIFE
 * wrapper itself provides the strict-mode boundary in Chrome 111+.
 *
 * Rules:
 *  1. Remove the `"use strict";\n` line (injected after the banner by esbuild).
 *  2. Convert double-quoted string literals to single-quoted:
 *     - Escape any unescaped single quotes inside the string with `\'`.
 *     - Un-escape any unnecessarily escaped double quotes `\"` → `"`.
 *     - Leave template literals, regex literals, and comments untouched (they
 *       don't use the double-quoted string syntax this regex matches).
 *
 * This step is deterministic: the same source always produces the same output.
 *
 * @param {string} src - Raw esbuild output text.
 * @returns {string} Post-processed text with single-quoted string literals.
 */
function postProcess(src) {
  // Step 1: remove the "use strict"; line esbuild injects.
  // It appears on the line immediately after the banner comment.
  let out = src.replace(/^"use strict";\n/m, '');

  // Step 2: convert double-quoted string literals to single-quoted.
  // Match a double-quoted string: "..." where the interior may contain:
  //   - any character that is not " or \
  //   - any backslash-escape sequence
  // We deliberately exclude strings that contain a newline to avoid
  // accidentally matching across template-literal spans.
  out = out.replace(/"((?:[^"\\]|\\.)*)"/g, (_match, inner) => {
    // Escape unescaped single quotes inside the former double-quoted string.
    const escaped = inner.replace(/(?<!\\)'/g, "\\'");
    // Un-escape \\" → " (esbuild escapes double-quotes inside double-quoted
    // strings; they no longer need escaping inside single-quoted strings).
    const unescaped = escaped.replace(/\\"/g, '"');
    return `'${unescaped}'`;
  });

  return out;
}

/**
 * Build the extension content script bundle.
 *
 * @param {string} [outfile] - Destination path for content.js.
 *   Defaults to packages/recorder-extension/content.js when called from CLI.
 *   Pass an absolute temp-file path when calling from tests.
 */
export async function buildExtension(outfile = DEFAULT_OUTFILE) {
  // Build to a temporary in-memory result first so we can post-process before
  // writing to the final destination.
  const result = await esbuild.build({
    entryPoints: [ENTRY],
    bundle: true,
    format: 'iife',
    platform: 'browser',
    target: 'chrome111',
    // Determinism requirements:
    minify: false,       // preserve symbol names; keeps popup.js method lookup stable
    sourcemap: false,    // no path-embedding; identical bytes across machines
    legalComments: 'none', // strip licence blocks to avoid path/version churn
    write: false,        // capture output in memory for post-processing
    // Fixed banner — DO NOT add a timestamp or build-hash here; it breaks
    // the byte-identical reproducibility assertion in build-parity.test.ts.
    banner: { js: BANNER },
  });

  const rawText = result.outputFiles[0].text;
  const processedText = postProcess(rawText);
  fs.writeFileSync(outfile, processedText, 'utf-8');
}

// ─── CLI entry-point ──────────────────────────────────────────────────────────
// When invoked directly (`node build.mjs [--outfile=...]`) parse the optional
// flag and run the build, exiting non-zero on failure so CI + the npm script
// `"build": "node build.mjs && node scripts/validate.mjs"` aborts on error.

const isMain =
  process.argv[1] && path.resolve(process.argv[1]) === path.resolve(HERE, 'build.mjs');

if (isMain) {
  const outfileArg = process.argv
    .slice(2)
    .find((a) => a.startsWith('--outfile='));
  const outfile = outfileArg ? outfileArg.split('=').slice(1).join('=') : DEFAULT_OUTFILE;

  buildExtension(outfile).then(() => {
    console.log(`built: ${outfile}`);
  }).catch((err) => {
    console.error('build failed:', err);
    process.exit(1);
  });
}
