// GENERATED by build.mjs from @haywork/recorder — DO NOT EDIT BY HAND. Run `pnpm -F @haywork/recorder-extension build`.
(() => {
  // ../recorder/src/index.ts
  var MAX_ARGS = 10;
  var MAX_ARG_LEN = 2e3;
  var CONSOLE_LEVELS = ['log', 'info', 'warn', 'error', 'debug'];
  var DEFAULT_SELECTORS = ['data-segment-id', 'data-testid', 'data-cuit-id'];
  var POINTER_TYPES = ['pointerdown', 'pointermove', 'pointerup'];
  var PHASE_FROM_TYPE = {
    pointerdown: 'down',
    pointermove: 'move',
    pointerup: 'up'
  };
  function semanticName(el, attrs) {
    for (const a of attrs) {
      const v = el.getAttribute(a);
      if (v) return v;
    }
    return void 0;
  }
  function cssPathOf(el) {
    const parts = [];
    let node = el;
    while (node && node.nodeType === 1 && parts.length < 8) {
      let part = node.tagName.toLowerCase();
      if (node.id) {
        part += `#${node.id}`;
        parts.unshift(part);
        break;
      }
      const cls = (node.getAttribute('class') ?? '').trim().split(/\s+/).filter(Boolean).slice(0, 2);
      if (cls.length) part += '.' + cls.join('.');
      parts.unshift(part);
      node = node.parentElement;
    }
    return parts.join(' > ');
  }
  function flattenSnapshot(snapshot, path = '') {
    const out = [];
    for (const [k, v] of Object.entries(snapshot)) {
      const next = path ? `${path}.${k}` : k;
      if (Array.isArray(v)) {
        out.push([`${next}.length`, v.length]);
        v.forEach((item, i) => {
          if (item !== null && typeof item === 'object') {
            out.push(...flattenSnapshot(item, `${next}[${i}]`));
          } else {
            out.push([`${next}[${i}]`, item]);
          }
        });
      } else if (v !== null && typeof v === 'object') {
        out.push(...flattenSnapshot(v, next));
      } else {
        out.push([next, v]);
      }
    }
    return out;
  }
  var Recorder = class {
    sessionId;
    vendor;
    snapshotProvider;
    now;
    doc;
    selectors;
    captureConsoleOpt;
    captureErrorsOpt;
    redactConsoleArg;
    events = [];
    seq = 0;
    startedAt = null;
    listeners = [];
    lastSnapshotKey = null;
    /** Re-entrancy guard: prevents recursive console calls from infinite-looping. */
    consoleCapturing = false;
    constructor(options) {
      this.sessionId = options.sessionId;
      this.vendor = options.vendor ?? 'cuit';
      this.snapshotProvider = options.snapshotProvider;
      this.now = options.now ?? (() => Date.now());
      if (options.document) {
        this.doc = options.document;
      } else if (typeof document !== 'undefined') {
        this.doc = document;
      } else {
        throw new Error('Recorder: no document available; pass options.document');
      }
      this.selectors = options.semanticSelectors ?? DEFAULT_SELECTORS;
      this.captureConsoleOpt = options.captureConsole ?? true;
      this.captureErrorsOpt = options.captureErrors ?? true;
      this.redactConsoleArg = options.redactConsoleArg;
    }
    start() {
      if (this.startedAt !== null) return;
      this.startedAt = this.now();
      const baseUrl = typeof this.doc.defaultView !== 'undefined' && this.doc.defaultView ? this.doc.defaultView.location.href : '';
      const nav = {
        seq: this.nextSeq(),
        vendor: this.vendor,
        vendorEventId: `${this.sessionId}-nav-0`,
        ts: 0,
        wallClock: this.startedAt,
        type: 'nav',
        url: baseUrl
      };
      this.events.push(nav);
      this.captureSnapshot();
      const onPointer = (type) => (ev) => {
        const pe = ev;
        const target = pe.target;
        if (!target) return;
        const name = semanticName(target, this.selectors);
        const cssPath = cssPathOf(target);
        const event = {
          seq: this.nextSeq(),
          vendor: this.vendor,
          vendorEventId: `${this.sessionId}-p-${this.seq}`,
          ts: this.relativeTs(),
          wallClock: this.now(),
          type: 'pointer',
          phase: PHASE_FROM_TYPE[type],
          targetSelector: cssPath,
          ...name !== void 0 ? { targetName: name } : {},
          x: Math.round(pe.clientX),
          y: Math.round(pe.clientY),
          pointerId: pe.pointerId ?? 0
        };
        this.events.push(event);
        if (type === 'pointerup' || type === 'pointerdown') {
          this.captureSnapshot();
        }
      };
      for (const t of POINTER_TYPES) {
        const handler = onPointer(t);
        this.doc.addEventListener(t, handler, true);
        this.listeners.push(() => this.doc.removeEventListener(t, handler, true));
      }
      this.installConsoleCapture();
      this.installKeyboardCapture();
    }
    stop() {
      for (const off of this.listeners) off();
      this.listeners = [];
      this.captureSnapshot();
    }
    /** Explicit snapshot — useful between manual interactions. */
    captureSnapshot() {
      if (!this.snapshotProvider) return;
      let raw;
      try {
        raw = this.snapshotProvider();
      } catch {
        return;
      }
      if (!raw) return;
      const flattened = flattenSnapshot(raw);
      const key = JSON.stringify(flattened);
      if (key === this.lastSnapshotKey) return;
      this.lastSnapshotKey = key;
      for (const [path, value] of flattened) {
        const ev = {
          seq: this.nextSeq(),
          vendor: this.vendor,
          vendorEventId: `${this.sessionId}-snap-${this.seq}`,
          ts: this.relativeTs(),
          wallClock: this.now(),
          type: 'state-snapshot',
          path,
          value
        };
        this.events.push(ev);
      }
    }
    export() {
      if (this.startedAt === null) {
        throw new Error('Recorder.export(): recorder was never started');
      }
      const url = this.events.find((e) => e.type === 'nav')?.url ?? '';
      return {
        sessionId: this.sessionId,
        vendor: this.vendor,
        createdAt: this.startedAt,
        url,
        events: [...this.events]
      };
    }
    /** Number of events captured so far (useful for live dashboards). */
    size() {
      return this.events.length;
    }
    // ─── Keyboard / text-input capture ────────────────────────────────────────
    /**
     * Installs an `input` event listener on the document that captures text typed
     * into input fields as `KeyboardEvent` (type:'keyboard') entries.
     *
     * The captured `value` is the full current text value of the element at the
     * time of the event, not individual keystroke deltas.  This matches the
     * @haywork/types KeyboardEvent contract and what spec-gen needs to replay typing.
     *
     * Must be called inside `start()` after `startedAt` is set.
     */
    installKeyboardCapture() {
      const onInput = (ev) => {
        const target = ev.target;
        if (!target) return;
        const value = typeof target.value === 'string' ? target.value : '';
        const name = semanticName(target, this.selectors);
        const cssPath = cssPathOf(target);
        const kbEvent = {
          seq: this.nextSeq(),
          vendor: this.vendor,
          vendorEventId: `${this.sessionId}-kb-${this.seq}`,
          ts: this.relativeTs(),
          wallClock: this.now(),
          type: 'keyboard',
          targetSelector: cssPath,
          ...name !== void 0 ? { targetName: name } : {},
          value
        };
        this.events.push(kbEvent);
      };
      this.doc.addEventListener('input', onInput, true);
      this.listeners.push(() => this.doc.removeEventListener('input', onInput, true));
    }
    // ─── Console / error capture ───────────────────────────────────────────────
    /**
     * Safely convert a single console argument to a string suitable for storage.
     * - Primitives are String()-coerced.
     * - Objects / functions are JSON.stringify'd; circular/non-serialisable values
     *   fall back to String(v).
     * - The result is capped at MAX_ARG_LEN with a '…' suffix.
     * Never throws.
     */
    safeStringifyArg(v) {
      let s;
      if (v === null) {
        s = 'null';
      } else if (typeof v === 'undefined') {
        s = 'undefined';
      } else if (typeof v === 'symbol') {
        s = v.toString();
      } else if (typeof v === 'object' || typeof v === 'function') {
        try {
          s = JSON.stringify(v) ?? String(v);
        } catch {
          s = String(v);
        }
      } else {
        s = String(v);
      }
      if (s.length > MAX_ARG_LEN) {
        return s.slice(0, MAX_ARG_LEN - 1) + '\u2026';
      }
      return s;
    }
    /**
     * Serialise and cap a raw arguments array.
     * - Applies `redactConsoleArg` if provided.
     * - Caps to MAX_ARGS; appends an overflow marker for extras.
     * - Returns string[] so args are always JSON-serialisable.
     */
    serialiseArgs(rawArgs) {
      const overflow = rawArgs.length > MAX_ARGS ? rawArgs.length - MAX_ARGS : 0;
      const slice = rawArgs.slice(0, MAX_ARGS);
      const redact = this.redactConsoleArg;
      const serialised = slice.map((a) => {
        const v = redact ? redact(a) : a;
        return this.safeStringifyArg(v);
      });
      if (overflow > 0) {
        serialised.push(`+${overflow} more`);
      }
      return serialised;
    }
    /**
     * Wraps each console level and registers a teardown in `this.listeners`.
     * Also installs window 'error' and 'unhandledrejection' handlers when
     * `captureErrors` is true.
     *
     * Must be called inside `start()` after `startedAt` is set.
     */
    installConsoleCapture() {
      const win = this.doc.defaultView ?? null;
      const cons = win?.console ?? globalThis.console;
      if (this.captureConsoleOpt) {
        for (const level of CONSOLE_LEVELS) {
          const originalUnbound = cons[level];
          const originalBound = originalUnbound.bind(cons);
          const wrapper = (...args) => {
            originalBound(...args);
            if (this.consoleCapturing) return;
            this.consoleCapturing = true;
            try {
              const serialisedArgs = this.serialiseArgs(args);
              const overflowRe = /^\+\d+ more$/;
              const message = serialisedArgs.filter((a) => !overflowRe.test(a)).join(' ');
              const ev = {
                seq: this.nextSeq(),
                vendor: this.vendor,
                vendorEventId: `${this.sessionId}-con-${this.seq}`,
                ts: this.relativeTs(),
                wallClock: this.now(),
                type: 'console',
                level,
                message,
                args: serialisedArgs
              };
              this.events.push(ev);
            } finally {
              this.consoleCapturing = false;
            }
          };
          cons[level] = wrapper;
          this.listeners.push(() => {
            cons[level] = originalUnbound;
          });
        }
      }
      if (this.captureErrorsOpt && win) {
        const onWindowError = (ev) => {
          const message = ev.message ?? String(ev);
          const err = ev.error;
          const stack = err instanceof Error && typeof err.stack === 'string' ? err.stack : void 0;
          const errorEvt = {
            seq: this.nextSeq(),
            vendor: this.vendor,
            vendorEventId: `${this.sessionId}-err-${this.seq}`,
            ts: this.relativeTs(),
            wallClock: this.now(),
            type: 'error-event',
            message,
            ...stack !== void 0 ? { stack } : {},
            source: 'window.error'
          };
          this.events.push(errorEvt);
          const consoleEv = {
            seq: this.nextSeq(),
            vendor: this.vendor,
            vendorEventId: `${this.sessionId}-con-${this.seq}`,
            ts: this.relativeTs(),
            wallClock: this.now(),
            type: 'console',
            level: 'error',
            message,
            args: [message]
          };
          this.events.push(consoleEv);
        };
        win.addEventListener('error', onWindowError);
        this.listeners.push(() => win.removeEventListener('error', onWindowError));
        const onUnhandledRejection = (ev) => {
          const reason = ev.reason;
          let message;
          let stack;
          if (reason instanceof Error) {
            message = reason.message;
            stack = reason.stack;
          } else {
            message = String(reason ?? 'unhandled rejection');
          }
          const errorEvt = {
            seq: this.nextSeq(),
            vendor: this.vendor,
            vendorEventId: `${this.sessionId}-rej-${this.seq}`,
            ts: this.relativeTs(),
            wallClock: this.now(),
            type: 'error-event',
            message,
            ...stack !== void 0 ? { stack } : {},
            source: 'unhandledrejection'
          };
          this.events.push(errorEvt);
          const consoleEv = {
            seq: this.nextSeq(),
            vendor: this.vendor,
            vendorEventId: `${this.sessionId}-con-${this.seq}`,
            ts: this.relativeTs(),
            wallClock: this.now(),
            type: 'console',
            level: 'error',
            message,
            args: [message]
          };
          this.events.push(consoleEv);
        };
        win.addEventListener('unhandledrejection', onUnhandledRejection);
        this.listeners.push(() => win.removeEventListener('unhandledrejection', onUnhandledRejection));
      }
    }
    // ─── Sequence / timing helpers ─────────────────────────────────────────────
    nextSeq() {
      const s = this.seq;
      this.seq += 1;
      return s;
    }
    relativeTs() {
      if (this.startedAt === null) return 0;
      return this.now() - this.startedAt;
    }
  };
  function cuitDebugProvider() {
    if (typeof window === 'undefined') return null;
    const dbg = window.__cuitDebug;
    if (!dbg || typeof dbg.getState !== 'function') return null;
    try {
      return dbg.getState();
    } catch {
      return null;
    }
  }

  // src/content.entry.ts
  var existing = window.__cuitRecorder;
  if (existing) {
  } else {
    let active = null;
    const api = {
      start(options) {
        if (active) return { ok: false, error: 'already-recording' };
        const sessionId = options && options.sessionId || `cuit-${Date.now()}`;
        active = new Recorder({
          sessionId,
          vendor: 'cuit',
          snapshotProvider: cuitDebugProvider
          // captureConsole and captureErrors both default to true in Recorder —
          // no need to pass them explicitly.  This means console.{log,info,warn,
          // error,debug} and window error/unhandledrejection are captured
          // automatically with zero extra code here.
        });
        active.start();
        return { ok: true, sessionId };
      },
      stop() {
        if (!active) return { ok: false, error: 'not-recording' };
        active.stop();
        const out = active.export();
        active = null;
        return { ok: true, session: out };
      },
      status() {
        const hasCuitDebug = Boolean(
          window.__cuitDebug
        );
        if (!active) return { recording: false, hasCuitDebug };
        return {
          recording: true,
          sessionId: active.sessionId,
          eventCount: active.size(),
          hasCuitDebug
        };
      }
    };
    window.__cuitRecorder = api;
    document.documentElement.dataset['cuitRecorderInstalled'] = 'true';
  }
})();
