/**
 * packages/mcp-local/test/shim.test.ts
 *
 * FAILING tests for the Local mock MCP shim.
 * These tests define the contract for all four PRODUCT-DELIVERY tools:
 *   cuit__generate_spec_from_session
 *   cuit__run_spec
 *   cuit__close_loop
 *   cuit__detect_app_shape
 *
 * Every test MUST fail until the implementation is complete.
 * The test file never throws — each tool returns an AX envelope.
 * Zero network calls are permitted in the close_loop path.
 */

import { readFileSync, mkdirSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, test, vi, afterEach } from 'vitest';

import {
  generateSpecTool,
  runSpecTool,
  detectAppShapeTool,
  closeLoopTool,
  type AxEnvelope,
  type StateMismatch,
  type SnapshotProvider,
} from '../src/index.js';

import { normalizeJamSession, type RawJamSession } from '@haywork/adapter-jam';
import type { GeneratedSpec, SessionEvent } from '@haywork/cuit-types';

// ---------------------------------------------------------------------------
// Fixture loading helpers
// ---------------------------------------------------------------------------

const HERE = dirname(fileURLToPath(import.meta.url));
const FIXTURES_DIR = join(HERE, '../../../fixtures');

function loadSegmentCollision(): RawJamSession {
  return JSON.parse(
    readFileSync(join(FIXTURES_DIR, 'segment-collision.json'), 'utf-8'),
  ) as RawJamSession;
}

function loadTranslateUiReact(): { vendor: 'cuit'; events: SessionEvent[]; url: string } {
  const raw = JSON.parse(
    readFileSync(join(FIXTURES_DIR, 'translate-ui-react-drag-after-resize.json'), 'utf-8'),
  ) as { vendor: string; events: SessionEvent[]; url: string };
  return raw as { vendor: 'cuit'; events: SessionEvent[]; url: string };
}

// ---------------------------------------------------------------------------
// Computed fixture constants — derived independently, NOT from the tool output.
// These values are computed from the raw fixture data before any tool call
// so the tests never use the function under test as its own oracle.
// ---------------------------------------------------------------------------

// segment-collision: pointer-down x=50, pointer-up x=150 → dx=100
// Both values are read from the fixture file directly.
const SEG_COLLISION_FIXTURE = loadSegmentCollision();
const SEG_COLLISION_POINTER_DOWN_X = (() => {
  const pd = SEG_COLLISION_FIXTURE.events.find(
    (e): e is Record<string, unknown> =>
      (e as Record<string, unknown>)['type'] === 'pointer' &&
      (e as Record<string, unknown>)['phase'] === 'down',
  );
  return pd?.['x'] as number;
})();
const SEG_COLLISION_POINTER_UP_X = (() => {
  const pu = [...SEG_COLLISION_FIXTURE.events]
    .reverse()
    .find(
      (e): e is Record<string, unknown> =>
        (e as Record<string, unknown>)['type'] === 'pointer' &&
        (e as Record<string, unknown>)['phase'] === 'up',
    );
  return pu?.['x'] as number;
})();
const SEG_COLLISION_EXPECTED_DX =
  SEG_COLLISION_POINTER_UP_X - SEG_COLLISION_POINTER_DOWN_X;

// translate-ui-react: pointer-down x=404, pointer-up x=424 → dx=20
// targetName=seg-1, nav url
const TUR_FIXTURE = loadTranslateUiReact();
const TUR_POINTER_DOWN_X = (() => {
  const pd = TUR_FIXTURE.events.find(
    (e) => e.type === 'pointer' && (e as { phase: string }).phase === 'down',
  );
  return (pd as { x: number } | undefined)?.x ?? 0;
})();
const TUR_POINTER_UP_X = (() => {
  const pu = [...TUR_FIXTURE.events]
    .reverse()
    .find(
      (e) => e.type === 'pointer' && (e as { phase: string }).phase === 'up',
    );
  return (pu as { x: number } | undefined)?.x ?? 0;
})();
const TUR_EXPECTED_DX = TUR_POINTER_UP_X - TUR_POINTER_DOWN_X;
const TUR_NAV_URL = TUR_FIXTURE.url;

// The test name is dynamically generated by spec-gen from the interaction shape.
// For segment-collision: pointer-down at seg-0, dx=+100px, assert path=segments[0].x
// Formula: "drag <targetName> by +<dx>px updates <assertPath>"
const SPEC_GEN_TEST_NAME = 'drag seg-0 by +100px updates segments[0].x';
const ASSERT_PATH = 'segments[0].x';

// ---------------------------------------------------------------------------
// Helper: build a minimal snapshotProvider seeded to the spec's expectedFinalState
// ---------------------------------------------------------------------------

function providerFromExpected(spec: GeneratedSpec): SnapshotProvider {
  const snapshot: Record<string, unknown> = {};
  for (const { path, value } of spec.expectedFinalState) {
    snapshot[path] = value;
  }
  return () => snapshot;
}

function providerWithDelta(spec: GeneratedSpec, delta: number): SnapshotProvider {
  const snapshot: Record<string, unknown> = {};
  for (const { path, value } of spec.expectedFinalState) {
    snapshot[path] = (value as number) + delta;
  }
  return () => snapshot;
}

// ---------------------------------------------------------------------------
// Guard: ensure no real network calls fire in close_loop
// ---------------------------------------------------------------------------

afterEach(() => {
  vi.restoreAllMocks();
});

// ---------------------------------------------------------------------------
// 1. cuit__generate_spec_from_session — Jam session normalization
// ---------------------------------------------------------------------------

describe('cuit__generate_spec_from_session', () => {
  test('normalizes a raw Jam session and returns an ok AX envelope with serialized spec', async () => {
    const result = await generateSpecTool({ session: SEG_COLLISION_FIXTURE });

    expect(result.outcome).toBe('ok');
    expect(result.data).not.toBeNull();

    const spec = result.data!.spec;
    expect(spec.testName).toBe(SPEC_GEN_TEST_NAME);

    // Verify dispatchDrag primitive exists with the independently-computed dx
    const dragPrim = spec.primitives.find((p) => p.kind === 'dispatchDrag');
    expect(dragPrim).toBeDefined();
    expect(dragPrim).toMatchObject({
      kind: 'dispatchDrag',
      dx: SEG_COLLISION_EXPECTED_DX,
    });

    // Verify assertStateEquals exists for ASSERT_PATH
    const assertPrim = spec.primitives.find((p) => p.kind === 'assertStateEquals');
    expect(assertPrim).toBeDefined();
    expect(assertPrim).toMatchObject({
      kind: 'assertStateEquals',
      path: ASSERT_PATH,
      value: SEG_COLLISION_EXPECTED_DX,
    });

    // serialized must reference @haywork/cuit-harness (not an empty string, not a placeholder)
    const serialized = result.data!.serialized;
    expect(typeof serialized).toBe('string');
    expect(serialized.length).toBeGreaterThan(0);
    expect(serialized).toContain("from '@haywork/cuit-harness'");

    // next_actions must reference the run-spec tool
    expect(result.next_actions.some((a) => a.includes('cuit__run_spec'))).toBe(true);
  });

  test('passes a pre-normalized cuit session through without re-normalizing (resize-then-drag shape)', async () => {
    // TUR fixture vendor='cuit', already-typed SessionEvent[]
    // This shape has 1 nav + 12 snapshots + 4 pointer events
    const result = await generateSpecTool({
      session: TUR_FIXTURE,
    });

    expect(result.outcome).toBe('ok');
    expect(result.data).not.toBeNull();

    const spec = result.data!.spec;

    // The nav url from the cuit session must flow through to spec.url
    expect(spec.url).toBe(TUR_NAV_URL);

    // The drag must reflect the cuit-session pointer deltas
    const dragPrim = spec.primitives.find((p) => p.kind === 'dispatchDrag');
    expect(dragPrim).toBeDefined();
    expect(dragPrim).toMatchObject({
      kind: 'dispatchDrag',
      dx: TUR_EXPECTED_DX,
    });
  });

  test('returns outcome=error for a session with empty events array and does NOT throw', async () => {
    const emptySession: RawJamSession = {
      sessionId: 'empty-test',
      vendor: 'jam',
      createdAt: '2026-01-01T00:00:00Z',
      url: 'http://localhost:5173/',
      events: [],
    };

    // The tool must NOT throw — any thrown error is itself a test failure.
    // We call the tool inside a try/catch and re-throw unexpected errors so
    // the assertion message is clear when the implementation is missing.
    let result: AxEnvelope<unknown>;
    try {
      result = await generateSpecTool({ session: emptySession });
    } catch (err) {
      throw new Error(
        `generateSpecTool threw instead of returning an error envelope: ${String(err)}`,
      );
    }

    expect(result!.outcome).toBe('error');
    expect(typeof result!.summary).toBe('string');
    expect(result!.summary.length).toBeGreaterThan(0);
    expect(result!.summary.toLowerCase()).toMatch(/empty|no events/);
    expect(result!.data).toBeNull();
    expect(Array.isArray(result!.next_actions)).toBe(true);
    expect(result!.next_actions.length).toBeGreaterThan(0);
  });
});

// ---------------------------------------------------------------------------
// 2. cuit__run_spec — GREEN path (snapshot matches expected)
// ---------------------------------------------------------------------------

describe('cuit__run_spec', () => {
  test('reports GREEN when injected snapshotProvider matches expectedFinalState', async () => {
    // First generate a spec to have a real contract to run against
    const genResult = await generateSpecTool({ session: SEG_COLLISION_FIXTURE });
    expect(genResult.outcome).toBe('ok');
    const spec = genResult.data!.spec;

    // Build the provider from the spec's own contract — not a magic literal
    const snapshotProvider = providerFromExpected(spec);

    const result = await runSpecTool({ spec, snapshotProvider });

    expect(result.outcome).toBe('ok');
    expect(result.data).not.toBeNull();
    expect(result.data!.passed).toBe(true);
    expect(result.data!.mismatches).toHaveLength(0);
    expect(typeof result.summary).toBe('string');
    expect(result.summary.toLowerCase()).toMatch(/pass/);
  });

  test('reports RED with precise field-level mismatch when snapshot diverges', async () => {
    const genResult = await generateSpecTool({ session: SEG_COLLISION_FIXTURE });
    expect(genResult.outcome).toBe('ok');
    const spec = genResult.data!.spec;

    // Parameterized delta — differ from the spec's expected value by a known offset
    const DELTA = 15;
    const snapshotProvider = providerWithDelta(spec, DELTA);

    const result = await runSpecTool({ spec, snapshotProvider });

    // The tool ran successfully — a red is not a tool failure
    expect(result.outcome).toBe('ok');
    expect(result.data).not.toBeNull();
    expect(result.data!.passed).toBe(false);
    expect(result.data!.mismatches).toHaveLength(1);

    // The mismatch oracle is computed from the spec contract + the delta,
    // NOT read back from the tool output.
    const expectedSpecValue = spec.expectedFinalState[0]!.value as number;
    const expectedMismatch: StateMismatch = {
      path: ASSERT_PATH,
      expected: expectedSpecValue,
      actual: expectedSpecValue + DELTA,
    };
    expect(result.data!.mismatches[0]).toEqual(expectedMismatch);
  });

  test('returns an AX envelope (not throw) when spec has no expected state entries', async () => {
    const emptySpec: GeneratedSpec = {
      testName: 'stub',
      url: '',
      primitives: [],
      expectedFinalState: [],
    };

    // The tool must never throw — wrap in try/catch so a throw surfaces clearly.
    let result: AxEnvelope<unknown>;
    try {
      result = await runSpecTool({ spec: emptySpec });
    } catch (err) {
      throw new Error(
        `runSpecTool threw instead of returning an envelope: ${String(err)}`,
      );
    }

    // An empty spec with no expectedFinalState should pass vacuously or report
    // explicitly — either way it must be a well-formed AX envelope.
    expect(['ok', 'error']).toContain(result!.outcome);
    expect(typeof result!.summary).toBe('string');
    expect(Array.isArray(result!.next_actions)).toBe(true);
  });
});

// ---------------------------------------------------------------------------
// 3. cuit__close_loop — end-to-end, zero network, chained AX envelope
// ---------------------------------------------------------------------------

describe('cuit__close_loop', () => {
  test('runs generate→run→report end-to-end on segment-collision fixture with NO network', async () => {
    // Guard: spy on globalThis.fetch BEFORE calling the tool
    const fetchSpy = vi.spyOn(globalThis, 'fetch').mockImplementation(() => {
      throw new Error('cuit__close_loop must not call fetch — zero network allowed');
    });

    // Independently compute the expected normalizedEventCount using the adapter.
    // This is the oracle; the tool result must match this count exactly.
    const independentlyNormalized = normalizeJamSession(SEG_COLLISION_FIXTURE);
    const expectedNormalizedEventCount = independentlyNormalized.length;

    // Generate a spec independently to build the snapshotProvider oracle
    const genResult = await generateSpecTool({ session: SEG_COLLISION_FIXTURE });
    expect(genResult.outcome).toBe('ok');
    const specForProvider = genResult.data!.spec;
    const snapshotProvider = providerFromExpected(specForProvider);

    const result = await closeLoopTool({
      session: SEG_COLLISION_FIXTURE,
      snapshotProvider,
    });

    // The fetch spy must record zero calls
    expect(fetchSpy).not.toHaveBeenCalled();

    expect(result.outcome).toBe('ok');
    expect(result.data).not.toBeNull();

    const data = result.data!;

    // All four pipeline steps must be present in order
    expect(data.steps).toEqual(['normalize', 'generate', 'run', 'report']);

    expect(data.specGenerated).toBe(true);
    expect(data.passed).toBe(true);

    // normalizedEventCount must equal the independently computed value — not a magic number
    expect(data.normalizedEventCount).toBe(expectedNormalizedEventCount);

    // next_actions must be an array of strings
    expect(Array.isArray(result.next_actions)).toBe(true);
    expect(result.next_actions.length).toBeGreaterThan(0);
  });

  test('returns outcome=ok with passed=false (RED) when snapshot diverges — bug-reproduction is a valid loop outcome', async () => {
    // A divergent snapshot provider: every path returns a different value
    const redProvider: SnapshotProvider = () => ({
      [ASSERT_PATH]: -9999,
    });

    const result = await closeLoopTool({
      session: SEG_COLLISION_FIXTURE,
      snapshotProvider: redProvider,
    });

    // Reproducing a RED is a valid outcome — outcome must be 'ok', not 'error'
    expect(result.outcome).toBe('ok');
    expect(result.data).not.toBeNull();
    expect(result.data!.passed).toBe(false);
    expect(result.data!.mismatches.length).toBeGreaterThan(0);
    // next_actions must instruct the agent to fix the issue
    expect(Array.isArray(result.next_actions)).toBe(true);
    expect(result.next_actions.length).toBeGreaterThan(0);
  });
});

// ---------------------------------------------------------------------------
// 4. cuit__detect_app_shape — framework + state lib + cuitDebug wiring
// ---------------------------------------------------------------------------

describe('cuit__detect_app_shape', () => {
  test('detects react + zustand + cuitDebug=true from a written temp dir', async () => {
    const dir = join(tmpdir(), `cuit-detect-test-react-${Date.now()}`);
    mkdirSync(join(dir, 'src'), { recursive: true });

    writeFileSync(
      join(dir, 'package.json'),
      JSON.stringify({
        name: 'react-zustand-app',
        dependencies: { react: '^18.3.1', zustand: '^4.5.0' },
      }),
    );
    writeFileSync(
      join(dir, 'src', 'App.tsx'),
      `// debug bridge\nwindow.__cuitDebug = { getState: () => ({}) };\n`,
    );

    const result = await detectAppShapeTool({ dir });

    expect(result.outcome).toBe('ok');
    expect(result.data).not.toBeNull();

    const data = result.data!;
    expect(data.framework).toBe('react');
    expect(data.stateLib).toBe('zustand');
    expect(data.cuitDebugWired).toBe(true);

    // next_actions should point to cuit-instrument (already wired → proceed to record)
    expect(Array.isArray(result.next_actions)).toBe(true);
    expect(result.next_actions.some((a) => a.length > 0)).toBe(true);
  });

  test('detects vue + cuitDebug=false from a second temp dir', async () => {
    const dir = join(tmpdir(), `cuit-detect-test-vue-${Date.now()}`);
    mkdirSync(join(dir, 'src'), { recursive: true });

    writeFileSync(
      join(dir, 'package.json'),
      JSON.stringify({
        name: 'vue-only-app',
        dependencies: { vue: '^3.4.0' },
      }),
    );
    writeFileSync(
      join(dir, 'src', 'main.ts'),
      `import { createApp } from 'vue';\n// no __cuitDebug here\n`,
    );

    const result = await detectAppShapeTool({ dir });

    expect(result.outcome).toBe('ok');
    expect(result.data).not.toBeNull();

    const data = result.data!;
    expect(data.framework).toBe('vue');
    expect(data.cuitDebugWired).toBe(false);

    // next_actions must instruct wiring window.__cuitDebug
    expect(Array.isArray(result.next_actions)).toBe(true);
    expect(
      result.next_actions.some((a) =>
        a.toLowerCase().includes('__cuitdebug') || a.toLowerCase().includes('wire'),
      ),
    ).toBe(true);
  });

  test('resolves next as the framework when both next and react are in deps', async () => {
    const dir = join(tmpdir(), `cuit-detect-test-next-${Date.now()}`);
    mkdirSync(dir, { recursive: true });

    writeFileSync(
      join(dir, 'package.json'),
      JSON.stringify({
        name: 'next-app',
        dependencies: { next: '^14.2.0', react: '^18.3.1', 'react-dom': '^18.3.1' },
      }),
    );

    const result = await detectAppShapeTool({ dir });

    expect(result.outcome).toBe('ok');
    expect(result.data!.framework).toBe('next');
  });

  test('returns ok with vanilla/unknown/false for a dir with no package.json', async () => {
    const dir = join(tmpdir(), `cuit-detect-test-empty-${Date.now()}`);
    mkdirSync(dir, { recursive: true });
    // Deliberately no package.json written

    // Must not throw on ENOENT — falls back to safe defaults.
    let result: AxEnvelope<unknown>;
    try {
      result = await detectAppShapeTool({ dir });
    } catch (err) {
      throw new Error(
        `detectAppShapeTool threw on missing package.json instead of returning an envelope: ${String(err)}`,
      );
    }

    expect(['ok', 'error']).toContain(result!.outcome);
    if (result!.outcome === 'ok') {
      const data = result!.data as { framework: string; stateLib: string; cuitDebugWired: boolean };
      expect(data.framework).toBe('vanilla');
      expect(data.stateLib).toBe('unknown');
      expect(data.cuitDebugWired).toBe(false);
    }
  });
});

// ---------------------------------------------------------------------------
// 5. AX envelope contract — all tools, every call produces a well-formed envelope
// ---------------------------------------------------------------------------

describe('AX envelope contract', () => {
  const AX_KEYS = ['outcome', 'summary', 'data', 'next_actions'] as const;
  const VALID_OUTCOMES = new Set(['ok', 'error']);

  function assertWellFormedEnvelope(envelope: AxEnvelope<unknown>, label: string): void {
    for (const key of AX_KEYS) {
      expect(
        Object.prototype.hasOwnProperty.call(envelope, key),
        `${label}: missing key "${key}"`,
      ).toBe(true);
    }
    expect(
      VALID_OUTCOMES.has(envelope.outcome),
      `${label}: outcome must be 'ok' or 'error', got "${String(envelope.outcome)}"`,
    ).toBe(true);
    expect(
      typeof envelope.summary,
      `${label}: summary must be a string`,
    ).toBe('string');
    expect(
      Array.isArray(envelope.next_actions),
      `${label}: next_actions must be an array`,
    ).toBe(true);
    expect(
      envelope.next_actions.every((a) => typeof a === 'string'),
      `${label}: every next_action must be a string`,
    ).toBe(true);
  }

  test('generateSpecTool — ok path returns well-formed AX envelope', async () => {
    const result = await generateSpecTool({ session: SEG_COLLISION_FIXTURE });
    assertWellFormedEnvelope(result, 'generateSpecTool[ok]');
  });

  test('generateSpecTool — error path returns well-formed AX envelope with null data', async () => {
    const emptySession: RawJamSession = {
      sessionId: 'empty',
      vendor: 'jam',
      createdAt: '2026-01-01T00:00:00Z',
      url: '',
      events: [],
    };
    const result = await generateSpecTool({ session: emptySession });
    assertWellFormedEnvelope(result, 'generateSpecTool[error]');
    expect(result.outcome).toBe('error');
    expect(result.data).toBeNull();
    // summary must mention the root cause
    expect(result.summary.length).toBeGreaterThan(0);
  });

  test('runSpecTool — ok path returns well-formed AX envelope', async () => {
    const genResult = await generateSpecTool({ session: SEG_COLLISION_FIXTURE });
    const spec = genResult.data!.spec;
    const result = await runSpecTool({
      spec,
      snapshotProvider: providerFromExpected(spec),
    });
    assertWellFormedEnvelope(result, 'runSpecTool[ok]');
  });

  test('closeLoopTool — ok path returns well-formed AX envelope', async () => {
    const genResult = await generateSpecTool({ session: SEG_COLLISION_FIXTURE });
    const spec = genResult.data!.spec;
    const result = await closeLoopTool({
      session: SEG_COLLISION_FIXTURE,
      snapshotProvider: providerFromExpected(spec),
    });
    assertWellFormedEnvelope(result, 'closeLoopTool[ok]');
  });

  test('detectAppShapeTool — ok path returns well-formed AX envelope', async () => {
    const dir = join(tmpdir(), `cuit-envelope-test-${Date.now()}`);
    mkdirSync(dir, { recursive: true });
    writeFileSync(
      join(dir, 'package.json'),
      JSON.stringify({ name: 'test-app', dependencies: { react: '^18.3.1' } }),
    );
    const result = await detectAppShapeTool({ dir });
    assertWellFormedEnvelope(result, 'detectAppShapeTool[ok]');
  });

  test('every tool envelope has exactly the four required keys — no extra, none missing', async () => {
    // Collect one envelope per tool to check key set exhaustively
    const dir = join(tmpdir(), `cuit-keys-test-${Date.now()}`);
    mkdirSync(dir, { recursive: true });
    writeFileSync(
      join(dir, 'package.json'),
      JSON.stringify({ name: 'keys-test', dependencies: { react: '^18.0.0' } }),
    );

    const genResult = await generateSpecTool({ session: SEG_COLLISION_FIXTURE });
    const spec = genResult.outcome === 'ok' ? genResult.data!.spec : null;

    const envelopes: Array<[string, AxEnvelope<unknown>]> = [
      ['generateSpecTool', genResult],
      ['detectAppShapeTool', await detectAppShapeTool({ dir })],
    ];

    if (spec !== null) {
      envelopes.push([
        'runSpecTool',
        await runSpecTool({ spec, snapshotProvider: providerFromExpected(spec) }),
      ]);
      envelopes.push([
        'closeLoopTool',
        await closeLoopTool({ session: SEG_COLLISION_FIXTURE, snapshotProvider: providerFromExpected(spec) }),
      ]);
    }

    for (const [label, envelope] of envelopes) {
      const keys = Object.keys(envelope).sort();
      expect(keys, `${label}: unexpected key set`).toEqual(
        [...AX_KEYS].sort(),
      );
    }
  });
});

// ---------------------------------------------------------------------------
// 6. serialized spec — no placeholder literals allowed
// ---------------------------------------------------------------------------

describe('serializeSpec — no placeholder literals in output', () => {
  const PLACEHOLDER_PATTERN = /\b(foo|bar|baz|todo|placeholder|fixme|stub|example\.com)\b/i;

  test('segment-collision serialized spec contains no placeholder literals', async () => {
    const result = await generateSpecTool({ session: SEG_COLLISION_FIXTURE });
    expect(result.outcome).toBe('ok');
    const serialized = result.data!.serialized;
    expect(PLACEHOLDER_PATTERN.test(serialized)).toBe(false);
  });

  test('translate-ui-react serialized spec contains no placeholder literals', async () => {
    const result = await generateSpecTool({ session: TUR_FIXTURE });
    expect(result.outcome).toBe('ok');
    const serialized = result.data!.serialized;
    expect(PLACEHOLDER_PATTERN.test(serialized)).toBe(false);
  });

  test('a minimal nav-only cuit session serialized spec contains no placeholder literals', async () => {
    // Interaction shape #3: nav + pointer-down + pointer-up, no snapshots
    const minimalCuitSession = {
      vendor: 'cuit' as const,
      events: [
        {
          seq: 0,
          vendor: 'cuit' as const,
          vendorEventId: 'min-nav-0',
          ts: 0,
          wallClock: 0,
          type: 'nav' as const,
          url: 'http://localhost:3000/',
        },
        {
          seq: 1,
          vendor: 'cuit' as const,
          vendorEventId: 'min-ptr-1',
          ts: 100,
          wallClock: 100,
          type: 'pointer' as const,
          phase: 'down' as const,
          targetSelector: '[data-segment-id="btn-0"]',
          targetName: 'btn-0',
          x: 200,
          y: 100,
          pointerId: 1,
        },
        {
          seq: 2,
          vendor: 'cuit' as const,
          vendorEventId: 'min-ptr-2',
          ts: 250,
          wallClock: 250,
          type: 'pointer' as const,
          phase: 'up' as const,
          targetSelector: '[data-segment-id="btn-0"]',
          targetName: 'btn-0',
          x: 260,
          y: 100,
          pointerId: 1,
        },
      ] satisfies SessionEvent[],
      url: 'http://localhost:3000/',
    };

    const result = await generateSpecTool({ session: minimalCuitSession });
    // Either ok (spec generated) or error (insufficient events) — either way no placeholder
    if (result.outcome === 'ok') {
      expect(PLACEHOLDER_PATTERN.test(result.data!.serialized)).toBe(false);
    } else {
      // error is acceptable for this minimal shape; just verify envelope is well-formed
      expect(typeof result.summary).toBe('string');
    }
  });
});
