/**
 * ApiReference.tsx
 *
 * Custom OpenAPI 3.0 renderer in CUIT voice. Reads
 * src/content/openapi.json (generated by `pnpm openapi:dump` in the
 * cuit-saas repo) and renders endpoint cards with method badges,
 * paths, descriptions, request/response schemas, and copy-paste
 * curl examples.
 *
 * Server component — no client-side JS shipped. Re-renders at build
 * time when openapi.json changes.
 */

import spec from "@/content/openapi.json";

// ─── Types matching what we generate ────────────────────────────────────────

type JsonSchema = {
  type?: string;
  description?: string;
  enum?: unknown[];
  example?: unknown;
  format?: string;
  items?: JsonSchema;
  properties?: Record<string, JsonSchema>;
  required?: string[];
  oneOf?: JsonSchema[];
  $ref?: string;
};

type Response = {
  description: string;
  content?: { "application/json"?: { schema?: JsonSchema } };
};

type Parameter = {
  name: string;
  in: "path" | "query" | "header";
  required?: boolean;
  schema?: JsonSchema;
  description?: string;
  example?: unknown;
};

type Operation = {
  summary?: string;
  description?: string;
  tags?: string[];
  security?: Array<Record<string, string[]>>;
  parameters?: Parameter[];
  requestBody?: {
    content: { "application/json": { schema: JsonSchema } };
    required?: boolean;
  };
  responses: Record<string, Response>;
};

type PathItem = Partial<
  Record<"get" | "post" | "put" | "patch" | "delete", Operation>
>;

type Spec = {
  openapi: string;
  info: { title: string; version: string; description?: string };
  servers: Array<{ url: string; description?: string }>;
  tags: Array<{ name: string; description?: string }>;
  paths: Record<string, PathItem>;
  components?: { schemas?: Record<string, JsonSchema> };
};

const OPENAPI_SPEC = spec as Spec;

// ─── Helpers ─────────────────────────────────────────────────────────────────

const METHOD_COLORS: Record<string, string> = {
  get: "bg-sky-500/15 text-sky-300 border-sky-500/40",
  post: "bg-emerald-500/15 text-emerald-300 border-emerald-500/40",
  put: "bg-amber-500/15 text-amber-300 border-amber-500/40",
  patch: "bg-amber-500/15 text-amber-300 border-amber-500/40",
  delete: "bg-rose-500/15 text-rose-300 border-rose-500/40",
};

function resolveRef(ref: string, components: Spec["components"]): JsonSchema {
  // Resolve only $ref like "#/components/schemas/Foo"
  const m = /^#\/components\/schemas\/(.+)$/.exec(ref);
  if (!m) return { description: `unresolvable ref: ${ref}` };
  const name = m[1]!;
  return components?.schemas?.[name] ?? { description: `missing schema: ${name}` };
}

function inlineType(schema: JsonSchema | undefined, components: Spec["components"]): string {
  if (!schema) return "—";
  if (schema.$ref) {
    const inner = resolveRef(schema.$ref, components);
    return inlineType(inner, components);
  }
  if (schema.enum) return schema.enum.map((v) => JSON.stringify(v)).join(" | ");
  if (schema.type === "array") return `${inlineType(schema.items, components)}[]`;
  if (schema.format) return `${schema.type}<${schema.format}>`;
  return schema.type ?? "object";
}

function exampleForSchema(
  schema: JsonSchema | undefined,
  components: Spec["components"],
  seen = new Set<string>(),
): unknown {
  if (!schema) return null;
  if (schema.$ref) {
    if (seen.has(schema.$ref)) return null;
    seen.add(schema.$ref);
    return exampleForSchema(resolveRef(schema.$ref, components), components, seen);
  }
  if (schema.example !== undefined) return schema.example;
  if (schema.enum?.length) return schema.enum[0];
  if (schema.type === "array") return [exampleForSchema(schema.items, components, seen)];
  if (schema.type === "object" && schema.properties) {
    const o: Record<string, unknown> = {};
    for (const [k, v] of Object.entries(schema.properties)) {
      o[k] = exampleForSchema(v, components, seen);
    }
    return o;
  }
  if (schema.format === "uuid") return "00000000-0000-0000-0000-000000000000";
  if (schema.format === "date-time") return new Date(0).toISOString();
  switch (schema.type) {
    case "string":
      return "string";
    case "number":
    case "integer":
      return 0;
    case "boolean":
      return true;
    default:
      return null;
  }
}

function curlExample(
  method: string,
  pathPattern: string,
  server: string,
  op: Operation,
  components: Spec["components"],
): string {
  const path = pathPattern.replace(/{([^}]+)}/g, ":$1");
  const lines = [`curl -X ${method.toUpperCase()} '${server}${path}' \\`];
  const needsAuth = op.security?.some((s) => "bearerAuth" in s);
  if (needsAuth) lines.push("  -H 'authorization: Bearer <YOUR_TENANT_TOKEN>' \\");
  if (op.requestBody) {
    lines.push("  -H 'content-type: application/json' \\");
    const example = exampleForSchema(
      op.requestBody.content["application/json"].schema,
      components,
    );
    const body = JSON.stringify(example, null, 2)
      .split("\n")
      .map((l, i) => (i === 0 ? `  -d '${l}` : `     ${l}`))
      .join("\n");
    lines.push(`${body}'`);
  } else {
    // remove trailing backslash on last line
    lines[lines.length - 1] = lines[lines.length - 1]!.replace(/ \\$/, "");
  }
  return lines.join("\n");
}

// ─── Sub-components ──────────────────────────────────────────────────────────

function MethodBadge({ method }: { method: string }) {
  const cls = METHOD_COLORS[method] ?? "bg-zinc-700 text-zinc-200";
  return (
    <span className={`font-mono text-[11px] font-semibold uppercase px-2 py-0.5 rounded border ${cls}`}>
      {method}
    </span>
  );
}

function SchemaTable({
  schema,
  components,
}: {
  schema: JsonSchema | undefined;
  components: Spec["components"];
}) {
  if (!schema) return null;
  const resolved = schema.$ref ? resolveRef(schema.$ref, components) : schema;
  if (!resolved.properties) {
    return (
      <div className="font-mono text-xs text-[var(--text-tertiary)]">
        type: <span className="text-[var(--text-primary)]">{inlineType(resolved, components)}</span>
      </div>
    );
  }
  const required = new Set(resolved.required ?? []);
  return (
    <table className="w-full text-xs font-mono">
      <thead>
        <tr className="text-[var(--text-tertiary)] uppercase tracking-wider">
          <th className="text-left py-1.5 pr-4 font-normal">field</th>
          <th className="text-left py-1.5 pr-4 font-normal">type</th>
          <th className="text-left py-1.5 font-normal">notes</th>
        </tr>
      </thead>
      <tbody>
        {Object.entries(resolved.properties).map(([name, fieldSchema]) => (
          <tr key={name} className="border-t border-[var(--border-color)]">
            <td className="py-1.5 pr-4 text-[var(--text-primary)]">
              {name}
              {required.has(name) && <span className="text-rose-400 ml-0.5">*</span>}
            </td>
            <td className="py-1.5 pr-4 text-sky-300">{inlineType(fieldSchema, components)}</td>
            <td className="py-1.5 text-[var(--text-secondary)]">{fieldSchema.description ?? "—"}</td>
          </tr>
        ))}
      </tbody>
    </table>
  );
}

function ResponsesBlock({
  responses,
  components,
}: {
  responses: Record<string, Response>;
  components: Spec["components"];
}) {
  return (
    <div className="space-y-3">
      {Object.entries(responses).map(([code, res]) => {
        const schema = res.content?.["application/json"]?.schema;
        const isSuccess = code.startsWith("2");
        return (
          <div
            key={code}
            className="border border-[var(--border-color)] rounded-md p-3 bg-[var(--bg-secondary)]"
          >
            <div className="flex items-center gap-2 mb-2">
              <span
                className={`font-mono text-[11px] font-semibold px-2 py-0.5 rounded border ${
                  isSuccess
                    ? "bg-emerald-500/15 text-emerald-300 border-emerald-500/40"
                    : "bg-rose-500/15 text-rose-300 border-rose-500/40"
                }`}
              >
                {code}
              </span>
              <span className="text-xs text-[var(--text-secondary)]">{res.description}</span>
            </div>
            {schema && <SchemaTable schema={schema} components={components} />}
          </div>
        );
      })}
    </div>
  );
}

function EndpointCard({
  method,
  path,
  op,
  spec,
  serverUrl,
}: {
  method: string;
  path: string;
  op: Operation;
  spec: Spec;
  serverUrl: string;
}) {
  const tagName = op.tags?.[0] ?? "general";
  return (
    <article
      id={`${method}-${path.replace(/[^a-z0-9]/gi, "-")}`}
      className="border border-[var(--border-color)] rounded-lg overflow-hidden bg-[var(--bg-primary)]"
    >
      <header className="px-5 py-4 border-b border-[var(--border-color)] bg-[var(--bg-secondary)]">
        <div className="flex items-center gap-3 flex-wrap">
          <MethodBadge method={method} />
          <code className="font-mono text-sm text-[var(--text-primary)]">{path}</code>
          <span className="font-mono text-[10px] uppercase tracking-widest text-[var(--text-tertiary)] ml-auto">
            {tagName}
          </span>
        </div>
        {op.summary && (
          <p className="text-sm text-[var(--text-secondary)] mt-2">{op.summary}</p>
        )}
      </header>

      <div className="px-5 py-4 space-y-5">
        {op.description && (
          <p className="text-sm text-[var(--text-secondary)] leading-relaxed">{op.description}</p>
        )}

        {/* Path / query params */}
        {op.parameters && op.parameters.length > 0 && (
          <section>
            <h4 className="font-mono text-[10px] uppercase tracking-widest text-[var(--text-tertiary)] mb-2">
              parameters
            </h4>
            <table className="w-full text-xs font-mono">
              <thead>
                <tr className="text-[var(--text-tertiary)] uppercase tracking-wider">
                  <th className="text-left py-1.5 pr-4 font-normal">name</th>
                  <th className="text-left py-1.5 pr-4 font-normal">in</th>
                  <th className="text-left py-1.5 pr-4 font-normal">type</th>
                  <th className="text-left py-1.5 font-normal">notes</th>
                </tr>
              </thead>
              <tbody>
                {op.parameters.map((p) => (
                  <tr key={p.name + p.in} className="border-t border-[var(--border-color)]">
                    <td className="py-1.5 pr-4 text-[var(--text-primary)]">
                      {p.name}
                      {p.required && <span className="text-rose-400 ml-0.5">*</span>}
                    </td>
                    <td className="py-1.5 pr-4 text-[var(--text-tertiary)]">{p.in}</td>
                    <td className="py-1.5 pr-4 text-sky-300">{inlineType(p.schema, spec.components)}</td>
                    <td className="py-1.5 text-[var(--text-secondary)]">{p.description ?? "—"}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </section>
        )}

        {/* Request body */}
        {op.requestBody && (
          <section>
            <h4 className="font-mono text-[10px] uppercase tracking-widest text-[var(--text-tertiary)] mb-2">
              request body
            </h4>
            <SchemaTable
              schema={op.requestBody.content["application/json"].schema}
              components={spec.components}
            />
          </section>
        )}

        {/* Responses */}
        <section>
          <h4 className="font-mono text-[10px] uppercase tracking-widest text-[var(--text-tertiary)] mb-2">
            responses
          </h4>
          <ResponsesBlock responses={op.responses} components={spec.components} />
        </section>

        {/* curl example */}
        <section>
          <h4 className="font-mono text-[10px] uppercase tracking-widest text-[var(--text-tertiary)] mb-2">
            example — curl
          </h4>
          <pre className="text-xs font-mono bg-[var(--bg-tertiary)] border border-[var(--border-color)] rounded-md p-3 overflow-x-auto leading-relaxed text-[var(--text-primary)]">
            {curlExample(method, path, serverUrl, op, spec.components)}
          </pre>
        </section>
      </div>
    </article>
  );
}

// ─── Main ────────────────────────────────────────────────────────────────────

export function ApiReference() {
  const s = OPENAPI_SPEC;
  const serverUrl = s.servers[1]?.url ?? s.servers[0]?.url ?? "https://api.cuit.dev";

  // Group endpoints by tag.
  const byTag = new Map<string, Array<{ method: string; path: string; op: Operation }>>();
  for (const [path, item] of Object.entries(s.paths)) {
    for (const method of ["get", "post", "put", "patch", "delete"] as const) {
      const op = item[method];
      if (!op) continue;
      const tag = op.tags?.[0] ?? "general";
      if (!byTag.has(tag)) byTag.set(tag, []);
      byTag.get(tag)!.push({ method, path, op });
    }
  }

  const tagOrder = s.tags.map((t) => t.name);
  const orderedTags = [...byTag.keys()].sort(
    (a, b) => tagOrder.indexOf(a) - tagOrder.indexOf(b),
  );

  return (
    <div className="space-y-10">
      {orderedTags.map((tag) => {
        const tagMeta = s.tags.find((t) => t.name === tag);
        const endpoints = byTag.get(tag)!;
        return (
          <section key={tag} id={`tag-${tag}`}>
            <header className="mb-4">
              <h2 className="text-xl font-semibold text-[var(--text-primary)]">
                {tag}
                <span className="font-mono text-xs text-[var(--text-tertiary)] ml-3">
                  ({endpoints.length} {endpoints.length === 1 ? "endpoint" : "endpoints"})
                </span>
              </h2>
              {tagMeta?.description && (
                <p className="text-sm text-[var(--text-secondary)] mt-1">{tagMeta.description}</p>
              )}
            </header>
            <div className="space-y-6">
              {endpoints.map((e) => (
                <EndpointCard
                  key={`${e.method}-${e.path}`}
                  method={e.method}
                  path={e.path}
                  op={e.op}
                  spec={s}
                  serverUrl={serverUrl}
                />
              ))}
            </div>
          </section>
        );
      })}
    </div>
  );
}

export function ApiServerList() {
  return (
    <div className="space-y-2">
      {OPENAPI_SPEC.servers.map((server) => (
        <div
          key={server.url}
          className="flex items-baseline gap-3 font-mono text-xs"
        >
          <code className="text-[var(--text-primary)]">{server.url}</code>
          {server.description && (
            <span className="text-[var(--text-tertiary)]">— {server.description}</span>
          )}
        </div>
      ))}
    </div>
  );
}

export function ApiInfoMeta() {
  return (
    <div className="font-mono text-xs text-[var(--text-tertiary)] space-y-1">
      <div>OpenAPI {OPENAPI_SPEC.openapi}</div>
      <div>
        {OPENAPI_SPEC.info.title} v{OPENAPI_SPEC.info.version}
      </div>
    </div>
  );
}
